
package cn.yun.student.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentService", targetNamespace = "http://service.student.yun.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.yun.student.service.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentInfo", targetNamespace = "http://service.student.yun.cn/", className = "cn.yun.student.service.GetStudentInfo")
    @ResponseWrapper(localName = "getStudentInfoResponse", targetNamespace = "http://service.student.yun.cn/", className = "cn.yun.student.service.GetStudentInfoResponse")
    @Action(input = "http://service.student.yun.cn/StudentService/getStudentInfoRequest", output = "http://service.student.yun.cn/StudentService/getStudentInfoResponse")
    public Student getStudentInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
